name: 'Setup docker buildx'
description: 'Setup docker buildx'

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
      with:
        install: true

    - name: Get release version
      id: version_number
      shell: bash
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF:10}" >> $GITHUB_ENV
        echo "name=RELEASE_VERSION::${GITHUB_REF:10}" >>$GITHUB_OUTPUT
